apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-rollout
  namespace: team-mvp
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        image: todaywasawesome/colors:v0.0.1-secure #Available releases are blue, purple, yellow, v0.0.1-test (signed), v1.0.1-secure (signed)