apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-mvp
resources:
- namespace.yaml

helmChartInflationGenerator:
- name: podinfo
  chartHome: charts
  namespace: team-mvp
