apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-mvp
resources:
- namespace.yaml

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    namespace: team-mvp
    valuesInline:
      service:
        type: LoadBalancer

