apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer-a
resources:
- namespace.yaml

helmCharts:
  - name: podinfo
    chartHome: charts/podinfo
    namespace: customer-a
