apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-mvp
resources:
- namespace.yaml

helmCharts:
- name: policy-playground # local chart, default path to "charts/"
  namespace: team-mvp
