apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    - filename: creds.conf
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: aws-creds
        key: creds
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    provider "aws" {
      credentials = "creds.conf"
    }
