apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-bucket-inline
spec:
  forProvider:
    source: Inline
    module: |
      resource "aws_s3_bucket" "example" {
        bucket = "my-tf-crossplane-test-bucket"
      }
