apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/open-policy-agent/gatekeeper-library/library  # OPA Gatekeeper - apply all template
# - constraints.yaml # apply the actual constrains using the templates above
- check-image.yaml  # Kyverno policy - validate image signature
