apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio-base
  labels:
    sourced.io/tier: dev
    sourced.io/tenant: platform
    sourced.io/kind: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.1
    chart: base
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
