apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crossplane
  namespace: argocd
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: crossplane-system
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/platform-crossplane/dev
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
