apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kyverno
  namespace: argocd
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: platform-kyverno
    server: {{ .Values.spec.destination.server }}
  # source:
  #   repoURL: {{ .Values.spec.source.repoURL }}
  #   targetRevision: {{ .Values.spec.source.targetRevision }}
  #   path: manifests/platform-kyverno/dev
  #   helm:
  #     values: |
  #       {{- toYaml .Values | nindent 8 }}
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 2.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    # - ServerSideApply=true
